### PR TITLE
Update zh.cn.lang

### PR DESCRIPTION
**Pull request by NancalaStarry**

### CODE REVIEW

**Comment by Hokorizero** [comment]
首先，傀儡不应该翻译成傀儡奴仆
沙石傀儡奴仆应该为砂石傀儡
干蘑菇护符...你这全都是机翻的吧？
请速速取消pr

**Comment by NancalaStarry** [comment]
不，我没有用机翻。你的新汉化文件pr还没有被作者接受，我暂时还不能改。

**Comment by TaoismDeepLake** [comment]
sandstone按原版真的不是砂岩吗？
Edit: nvm. Issue cleared.

**Comment by ChromaPIE** [comment]
~~The localization contained in this PR has several wrong translations among which exist translations that even differ from official standardized translations of Vanilla Minecraft.~~

~~It may caused by the original contributor's mindlessly copying lines from previous localization works, which may contain absurd fallacies.~~

~~Please do not merge it until fixing commits have been successfully updated.~~

~~Appreciate that.~~

Several problems cleared. Good to merge, but worths a wait.

**Comment by TaoismDeepLake** [comment]
As a native Chinese speaker and a Minecraft modder, I don't think this PR is "REDICULOUSLY WRONG", but some polishing is highly recommended. Like "sandstone", "沙石" is not what it is translated in Vanilla, it should be "砂岩". As for "奴仆", although you can pick it as the translation for "Minion" like MtG does, you can consider "随从" or "仆从". I advise everyone to remain calm on this.

**Comment by TaoismDeepLake** [comment]
If the author wonder what's the Chinese comments about, it’s mostly an unfortunate mistake in which translator A mistook  translator B's translation as terrible machine translation. Now it's basically fine and settled.

**Comment by TaoismDeepLake** [comment]
Wait a sec, “Earth Golemancy” is tranlsated into "傀儡学" and the "Earth" seems to be missing. I recommend considering this issue again.

**Comment by WinDanesz** [comment]
Thanks for working on a translation. Please be nice to each other and once you all reach a consensus the PR can be merged. cheers

**Comment by NancalaStarry** [comment]
Now the translation is ready to mega.

**Pull request merged**
